version: "3.7"
services:
  app:
    container_name: app
    build: app/.
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go/src/github.com/yoshi0202/grass-app/app
    working_dir: /go/src/github.com/yoshi0202/grass-app/app/src
  front:
    container_name: front
    build: front/.
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    working_dir: /app
  db:
    container_name: db
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
