FROM golang:1.15.2-buster
RUN go get -u -t -v github.com/gin-gonic/gin
RUN go get -u -t -v gorm.io/gorm
RUN go get -u -t -v gorm.io/driver/mysql
RUN mkdir -p /go/src/github.com/yoshi0202/grass-app/app